### PR TITLE
Update files to KiCad v8

### PR DESCRIPTION
**Pull request by martinjaeger**
No functional changes, the files were just saved using KiCad v8.

KiBot had to be updated in CI together with some adjustments to the filters.

### CODE REVIEW

**Comment by martinjaeger** [comment]
Looks like it fails to execute the following command in CI, which works perfectly fine locally:

```
git worktree add --detach --force /tmp/tmpt6g_vao6 main
```

**Comment by pasrom** [comment]
> Looks like it fails to execute the following command in CI, which works perfectly fine locally:
> 
> ```
> git worktree add --detach --force /tmp/tmpt6g_vao6 main
> ```

@martinjaeger I will investigate this over the next few days.

**Comment by martinjaeger** [comment]
Thanks @pasrom. Feel free to push directly to this branch for testing.

I have already verified that the GH Actions workflow has write permissions:
image

**Comment by pasrom** [comment]
This issue has been resolved! For a detailed description, please refer to the linked commit [here](https://github.com/LibreSolar/bms-c1/pull/61/commits/4d4e2a0df4a275b5f7c9ad9dba36cf5e2356cf22).

**Comment by martinjaeger** [comment]
Excellent, thanks a lot @pasrom.

**Review by pasrom — COMMENTED** [review]
👍

**Pull request merged**
